export const membresData = [
  {
    Nom: 'Jebri',
    Prenom: 'Abdelkhalek',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'President',
    tel: '0668728440',
  },
  {
    Nom: 'Elhouari',
    Prenom: 'Hicham',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Vice president',
    tel: '0629235879',
  },
  {
    Nom: 'Boudounit',
    Prenom: 'Elmehdi',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Secrétaire général',
    tel: '0613041853',
  },
  {
    Nom: 'Elmoutaki',
    Prenom: 'Abdeljalil',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Vice secraitair générale',
    tel: '0661098632',
  },
  {
    Nom: 'Marbouhi',
    Prenom: 'Abdellah',
    Image: '',
    text: 'Trésorier',
    tel: '0661240748',
  },
  {
    Nom: 'Ait Sliman',
    Prenom: 'Moulay Elhassan',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Vice trésorier',
    tel: '0771214975',
  },
  {
    Nom: 'Boukhazo',
    Prenom: 'Mohammed',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Conseiller',
    tel: '',
  },
  {
    Nom: 'Baâdil',
    Prenom: 'Lhsen',
    Image: '',
    text: 'Conseiller',
    tel: '',
  },
  {
    Nom: 'Garraoui',
    Prenom: 'Ibrahim',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Conseiller',
    tel: '',
  },
  {
    Nom: 'Imghri',
    Prenom: 'Abdelali',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Conseiller',
    tel: '',
  },
  {
    Nom: 'Ouagar',
    Prenom: 'Mohammed',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Conseiller',
    tel: '',
  },
  {
    Nom: 'Doulkifl',
    Prenom: 'Ibrahim',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Conseiller',
    tel: '',
  },
  {
    Nom: 'Diraâi',
    Prenom: 'Noureddine',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Conseiller',
    tel: '',
  },
  {
    Nom: 'Diraâi',
    Prenom: 'Abdeltif',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Conseiller',
    tel: '',
  },
  {
    Nom: 'Taouzi',
    Prenom: 'Mohammed',
    Image: '../../assets/membres/abdeljalil elmoutaki.jpg',
    text: 'Conseiller',
    tel: '',
  },
];
